# Generated by Django 4.2.16 on 2024-11-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("member", "Member"), ("pnm", "PNM"), ("chair", "Chair")],
                max_length=10,
            ),
        ),
    ]
