# Generated by Django 4.2.16 on 2024-09-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0002_hometown_pnm_delete_book_delete_genre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter hobbies or activities you enjoy",
                        max_length=200,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Involvement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter clubs or orgs you're involved in on campus",
                        max_length=200,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="pnm",
            name="summary",
        ),
        migrations.RemoveField(
            model_name="pnm",
            name="title",
        ),
        migrations.AddField(
            model_name="pnm",
            name="county",
            field=models.CharField(default="SOME STRING", max_length=200),
        ),
        migrations.AddField(
            model_name="pnm",
            name="firstname",
            field=models.CharField(default="SOME STRING", max_length=200),
        ),
        migrations.AddField(
            model_name="pnm",
            name="lastname",
            field=models.CharField(default="SOME STRING", max_length=200),
        ),
        migrations.AddField(
            model_name="pnm",
            name="major",
            field=models.CharField(default="SOME STRING", max_length=200),
        ),
        migrations.AddField(
            model_name="pnm",
            name="state",
            field=models.CharField(default="SOME STRING", max_length=200),
        ),
        migrations.RemoveField(
            model_name="pnm",
            name="hometown",
        ),
        migrations.DeleteModel(
            name="Hometown",
        ),
        migrations.AddField(
            model_name="pnm",
            name="activites",
            field=models.ManyToManyField(
                help_text="Select hobbies or activities for this PNM",
                to="djangoapp.activities",
            ),
        ),
        migrations.AddField(
            model_name="pnm",
            name="involvement",
            field=models.ManyToManyField(
                help_text="Select campus involement for this PNM",
                to="djangoapp.involvement",
            ),
        ),
        migrations.AddField(
            model_name="pnm",
            name="hometown",
            field=models.CharField(default="SOME STRING", max_length=200),
        ),
    ]
