# Generated by Django 4.2.16 on 2024-10-02 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("djangoapp", "0003_activities_involvement_remove_pnm_summary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view_results", "Can view PNM and member survey results")
                ],
            },
        ),
        migrations.RemoveField(
            model_name="pnm",
            name="activites",
        ),
        migrations.RemoveField(
            model_name="pnm",
            name="involvement",
        ),
        migrations.DeleteModel(
            name="Activities",
        ),
        migrations.DeleteModel(
            name="Involvement",
        ),
        migrations.DeleteModel(
            name="PNM",
        ),
    ]
